### ISSUE TITLE
Include action_returns in ABI

### ISSUE THREAD

**Issue by fschoell** [EOS-Nation/action-return-value#2]
currently the abi is missing the action_returns

**Comment by DenisCarriere** [comment]
Added ABI with `action_results`

https://github.com/EOS-Nation/action-return-value/blob/main/example.abi#L86-L102

Kylin
https://kylin.bloks.io/account/abc321444321?loadContract=true&tab=ABI&account=abc321444321&scope=abc321444321&limit=100
